name: C++ CI

on:
  push:
    branches:
      - main

    pull_rqeuest:
      branches:
        - main

jobs:
  build:
    name: SSGifier Unit tests
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Preparing environment
        run: sudo apt-get install -y clang

      - name: Building tests
        env:
          CXX: ./test/unit_tests.cpp Utils.cpp ArgumentQueue.cpp MessagePrinter.cpp FileProcessor.cpp ./test/catch_amalgamated.cpp
          CXXFLAGS: -std=c++17
          OUTPUTFILE: test.o
        run: clang++ $CXXFLAGS $CXX -o $OUTPUTFILE

      - name: Running tests
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ./test.o

      - name: Cleaning tests
        run: rm ./test.o
